### ISSUE TITLE
Wiring the for the thumb cluster

### ISSUE THREAD

**Issue by mdeloughry** [aleung/mini-thumb-dactyl-keyboard#2]
Hi,

First off excuse my stupidity here this is my first dactyl build and the dactyl mini thumb just looks the right one for me.

So I just have a question, which I just can't seem to work out from the guide, but how am I best to wire the thumb cluster looking at https://raw.githubusercontent.com/aleung/mini-thumb-dactyl-keyboard/master/guide/wiring.jpg this is showing the other keyboard and I can't really decipher from this how to do the three switches.

Thanks in advance for any help and thank you for building the board as it's the first dactyl that hasn't really scared me off!

**Comment by aleung** [comment]
You need to design how to wire the thumb cluster by yourself. The wiring must match the setting of pins and layout in `config.h`. 

First draw a picture like below to define which row and column each key belongs to.
![](https://github.com/aleung/mini-thumb-dactyl-keyboard/blob/master/guide/layout-config.png?raw=true)

Then you can wire the keys according to the row and column.

Next step is to define the key matrix in circuit into `LAYOUT` macro in `config.h`. 

It's covered in the [firmware config](https://github.com/aleung/mini-thumb-dactyl-keyboard/blob/master/guide/index.md#config) section in the guide.

BTW, PR to improve the guide is welcome!

**Comment by aleung** [comment]
If you follow my `LAYOUT` in https://github.com/aleung/qmk_firmware/blob/my_dactyl_manuform/keyboards/handwired/dactyl_manuform/mine/keyboard.h , here is my wiring:
![keymap](https://user-images.githubusercontent.com/271538/137847451-3e869161-a063-4b0e-8725-8ba371391408.png)

**Comment by mdeloughry** [comment]
Many thanks for providing this! I will use yours as  a starter :)

And sure I'll make notes as I go through the build and will look at creating a PR if I have anything to add 👍 

Again thank you for the help!

**Comment by fabiano-amaral** [comment]
Are u joking that u puted the orange button? with the first column, now i know because my build isnt working 😆
