### ISSUE TITLE
ERROR: Can not run bin/qmk!

### ISSUE THREAD

**Issue by VegetarianLion258** [aleung/mini-thumb-dactyl-keyboard#4]
Hello, thanks for you sharing,
I got Error when I run the docker_build.sh
`ERROR: Can not run bin/qmk!

 Please run util/qmk_install.sh to install all the dependencies QMK requires.

make: *** [Makefile:505: handwired/dactyl_manuform/mine:default] Error 1
`
But I have run qmk_install.sh but nothing worked.
Do you know how to solve it? Or I lost something
Looking for you reply.

**Comment by aleung** [comment]
I just followed the QMK documentation, but I'm not sure if there have been any changes in reason years. Here is the link  https://docs.qmk.fm/#/getting_started_docker?id=docker-quick-start

You could try following the latest instructions in the link and ask for help in the QMK community if needed.

**Comment by VegetarianLion258** [comment]
Thanks four your reply,
I solve the problem by building QMK on my own laptop. And successfully make the keyboard follow your steps.
Thansk for your sharing again
